# Generated by Django 4.2.7 on 2023-12-01 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="category",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
