# Generated by Django 4.2.7 on 2024-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Major', 'major'), ('Class', 'class')], max_length=16),
        ),
    ]
