# Generated by Django 4.2.7 on 2024-06-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='major',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Major'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Major', 'major'), ('Course', 'course')], max_length=16),
        ),
    ]
