# Generated by Django 4.2.7 on 2023-11-28 07:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Superadmin', 'superadmin'), ('Admin', 'admin'), ('Member', 'member')], default='Member', max_length=15),
        ),
    ]
