name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_ADDRESS }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          key: ${{ secrets.VM_PRIVATE_KEY_CONTENT }}
          script: |
            whoami
